### ISSUE TITLE
Alexa no longer discovering Devices.

### ISSUE THREAD

**Issue by UberSlackr** [originallyus/node-red-contrib-alexa-local#33]
After recent update of alexa-local node, Alexa is no longer able to discover new device. Also any existing discovered device no longer work. ~~Alexa says they are "offline"~~ Amazon Alexa app shows them as "offline."

```
Welcome to Node-RED
28 Nov 13:32:44 - [info] Node-RED version: v0.17.5
28 Nov 13:32:44 - [info] Node.js  version: v6.12.0
28 Nov 13:32:44 - [info] Linux 4.9.35-v7+ arm LE
28 Nov 13:32:46 - [info] Loading palette nodes
28 Nov 13:32:55 - [info] Dashboard version 2.6.2 started at /ui
28 Nov 13:32:58 - [info] Settings file  : /home/pi/.node-red/settings.js
28 Nov 13:32:58 - [info] User directory : /home/pi/.node-red
28 Nov 13:32:58 - [info] Flows file     : /home/pi/.node-red/flows_pi2.json
28 Nov 13:32:58 - [info] Server now running at http://127.0.0.1:1880/
28 Nov 13:32:58 - [info] Starting flows
28 Nov 13:32:58 - [info] Started flows
AlexaLocalNode closing done..
```
I have mqtt broker running on same machine, no issues publishing to it from external device on the same network.
`

**Comment by swilson86** [comment]
Confirmed. I noticed this too in 0.3.3 and in version 0.3.5 Alexa will not discover the new device (node)

**Comment by Corundex** [comment]
Alexa can't interact with version 0.3.5.
I put back version 0.3.2 - and normal work is restored.

**Comment by torinnguyen** [comment]
This has been fixed in version 0.3.6. It was a typo mistake.

**Comment by swilson86** [comment]
Still not working in 0.3.6 I even deleted the nodes and reinstalled them. Alexa does not discover them.

**Comment by torinnguyen** [comment]
Can you update to 0.3.7 and check whether you'd see a yellow discovery status when you ask Alexa to do so?

![node-red 2017-11-29 10-48-00](https://user-images.githubusercontent.com/767320/33357105-df96ff1a-d4f2-11e7-8ce4-d74f4ba23485.png)

**Comment by UberSlackr** [comment]
Getting 
![image](https://user-images.githubusercontent.com/4933069/33357919-046c4088-d48b-11e7-8a91-75b04e801e04.png)

**Comment by UberSlackr** [comment]
Also note, that if command "Alexa turn on Ceiling Light" is give, not shows "on" but about 30-60 seconds later it goes back to "discovery."

**Comment by torinnguyen** [comment]
That is fine; expected behavior. Alexa actually perform multiple discovery requests now and then on her own. That was the reason I didn't want to show 'discovery' status in the previous versions. It's just confusing.

**Comment by UberSlackr** [comment]
Rather it didn't show "discovery" -- as it screws up a lot of my dashboard flow that check for the current status output of the Alexa-Local node.

**Comment by swilson86** [comment]
On version 0.3.7 I installed 2 nodes at the same time and hit Deploy. Both said Connected afterwards. I then asked Alexa to discover devices and one of the nodes did turn yellow displaying Discovery, the other node remained green and said Connected. Alexa did not discover any new nodes. Thus we are back to square one.

**Comment by swilson86** [comment]
More clues... I uninstalled 0.3.7 and deleted the nodes, went back to 0.3.2 and restarted node-red. Amazing but now 0.3.2 nodes are also not discovered by Alexa. So I went to 0.3.1 and verified in Manage Palette that 0.3.1 is truly installed. Still Alexa will not discover the node. Everything worked fine until 0.3.6
Here are the versions of things running if that helps:
29 Nov 14:20:51 - [info] Node-RED version: v0.17.5
29 Nov 14:20:51 - [info] Node.js  version: v8.9.1
29 Nov 14:20:51 - [info] Windows_NT 10.0.16299 x64 LE
29 Nov 14:20:52 - [info] Loading palette nodes
29 Nov 14:20:53 - [info] Dashboard version 2.6.2 started at /ui

**Comment by idumzaes** [comment]
I just installed for the first time and Alexa does not discover any devices created. I don't even know how to go about beginning to troubleshoot this issue.

**Comment by torinnguyen** [comment]
@swilson86 it looks like some other problem with your device. I can't tell what's wrong either.
@idumzaes can you take a look at the log from NodeRED? Please google for instructions.

**Comment by swilson86** [comment]
Thanks. I am suspecting something is not right in Node.js or npm as I upgraded them in the middle of testing. Too many variables now. I am also suspicious of the correct location for the folder named node-modules, and something about "global" mode. This has always been a mystery in Windows 10. Will investigate further on a raspberry pi and other Windows computer. Anxious to see what happens with idumzaes too.

**Comment by idumzaes** [comment]
I added multiple alexa-local nodes and named them. Alexa is still unable to find them.
I ran the node-red-log command and saw nothing to do with Alexa-Local.
I even attached the nodes to a debug node and it doesn't display anything.
I am unable to find any other logs for node-red.
All my other nodes and flows start up normally without any issues.

**Comment by torinnguyen** [comment]
what is the status shown under alexa node?

**Comment by idumzaes** [comment]
Normally shows as online. Just checked now and shows Discovery. 
Image attached. 

![ee6bd384-6aa9-47f9-8117-58d25116edd4](https://user-images.githubusercontent.com/25732005/33509391-2cf2252c-d6cf-11e7-8db3-e243e5b48042.jpeg)

**Comment by torinnguyen** [comment]
That looks normal. I've updated to version 0.3.8 with tons of debug logging. Can you try that and dump your logs here.

**Comment by idumzaes** [comment]
Updated to latest version, deleted previous Alexa nodes and created new ones. Same issue.
Unable to discover devices and nothing about it in Node-Red logs or in debug tab. 
Bummer. :/
![2bfaa23e-2f96-4712-aabd-bf82f8922118](https://user-images.githubusercontent.com/25732005/33511043-47e1958a-d6e2-11e7-892a-588d92a4aaca.jpeg)

**Comment by idumzaes** [comment]
I'm still trying to get it to work and nothing.
I've attached the complete message from debug tab output for both nodes I created.
![screen shot 2017-12-01 at 10 41 48 pm](https://user-images.githubusercontent.com/25732005/33511452-1a46fafa-d6e9-11e7-9c97-bd95c35aac23.png)
![screen shot 2017-12-01 at 10 41 38 pm](https://user-images.githubusercontent.com/25732005/33511454-1ed07952-d6e9-11e7-855c-571bf826bdea.png)

**Comment by torinnguyen** [comment]
please give me the log from nodered console itself, not debug log shown in
the editor

**Comment by idumzaes** [comment]
I did in the comment above.

**Comment by idumzaes** [comment]
`pi@bpi-iot-ros-ai:~ $ node-red-start

Start Node-RED

Once Node-RED has started, point a browser at http://10.0.1.46:1880
On Pi Node-RED works better with the Firefox or Chrome browser

Use   node-red-stop                          to stop Node-RED
Use   node-red-start                         to start Node-RED again
Use   node-red-log                           to view the recent log output
Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
Use   sudo systemctl disable nodered.service to disable autostart on boot

To find more nodes and example flows - go to http://flows.nodered.org

Starting as a systemd service.
Started Node-RED graphical event wiring tool..
1 Dec 22:01:45 - [info]
Welcome to Node-RED
===================
1 Dec 22:01:45 - [info] Node-RED version: v0.17.5
1 Dec 22:01:45 - [info] Node.js  version: v6.12.0
1 Dec 22:01:45 - [info] Linux 3.10.101-pine64 arm LE
1 Dec 22:01:46 - [info] Loading palette nodes
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
1 Dec 22:01:50 - [info] Dashboard version 2.6.2 started at /ui
1 Dec 22:01:50 - [info] Settings file  : /home/pi/.node-red/settings.js
1 Dec 22:01:50 - [info] User directory : /home/pi/.node-red
1 Dec 22:01:50 - [info] Flows file     : /home/pi/.node-red/flows_bpi-iot-ros-ai.json
1 Dec 22:01:50 - [info] Server now running at http://127.0.0.1:1881/
1 Dec 22:01:50 - [info] Starting flows
1 Dec 22:01:51 - [info] Started flows
1 Dec 22:01:51 - [info] [mqtt-broker:5e587bfc.d6cc74] Connected to broker: mqtt://localhost:1883
1 Dec 22:01:51 - [info] [mqtt-broker:d3606e5.fa40a9] Connected to broker: mqtt://localhost:1883
1 Dec 22:02:56 - [info] Stopping modified nodes
AlexaLocalNode closing done...
1 Dec 22:02:56 - [info] Stopped modified nodes
1 Dec 22:02:56 - [info] Starting modified nodes
1 Dec 22:02:56 - [info] Started modified nodes
1 Dec 22:03:33 - [info] Stopping modified nodes
1 Dec 22:03:33 - [info] Stopped modified nodes
1 Dec 22:03:33 - [info] Starting modified nodes
1 Dec 22:03:33 - [info] Started modified nodes
1 Dec 22:05:52 - [info] Stopping modified nodes
1 Dec 22:05:52 - [info] Stopped modified nodes
1 Dec 22:05:52 - [info] Starting modified nodes
1 Dec 22:05:52 - [info] Started modified nodes
1 Dec 22:06:31 - [info] Stopping modified nodes
1 Dec 22:06:31 - [info] Stopped modified nodes
1 Dec 22:06:31 - [info] Starting modified nodes
1 Dec 22:06:31 - [info] Started modified nodes
1 Dec 22:07:21 - [info] Stopping modified nodes
1 Dec 22:07:21 - [info] Stopped modified nodes
1 Dec 22:07:21 - [info] Starting modified nodes
1 Dec 22:07:21 - [info] Started modified nodes
1 Dec 22:08:22 - [info] Stopping modified nodes
1 Dec 22:08:22 - [info] Stopped modified nodes
1 Dec 22:08:22 - [info] Starting modified nodes
1 Dec 22:08:22 - [info] Started modified nodes
1 Dec 22:22:47 - [info] Stopping modified nodes
1 Dec 22:22:47 - [info] Stopped modified nodes
1 Dec 22:22:47 - [info] Starting modified nodes
1 Dec 22:22:47 - [info] Started modified nodes
1 Dec 22:40:44 - [info] Stopping modified nodes
1 Dec 22:40:44 - [info] Stopped modified nodes
1 Dec 22:40:44 - [info] Starting modified nodes
1 Dec 22:40:44 - [info] Started modified nodes
1 Dec 22:40:58 - [info] Stopping modified nodes
1 Dec 22:40:58 - [info] Stopped modified nodes
1 Dec 22:40:58 - [info] Starting modified nodes
1 Dec 22:40:58 - [info] Started modified nodes`

**Comment by swilson86** [comment]
I installed 0.3.8 on a second clean Windows 10 computer after installing the latest stable NodeJS, npm, git,  node-red, and beta node-red-dashboard. I then setup two nodes and both were detected by Alexa and fully functional. I will investigate my main computer running identical software which does not detect them.

**Comment by swilson86** [comment]
Here is the output from the main computer:

C:\Users\Scott\.node-red>npm outdated
Package                Current  Wanted  Latest  Location
node-red-dashboard  2.6.3-beta     git     git  node-red-project

C:\Users\Scott\.node-red>node-red
2 Dec 00:59:38 - [info]

Welcome to Node-RED
===================

2 Dec 00:59:38 - [info] Node-RED version: v0.17.5
2 Dec 00:59:38 - [info] Node.js  version: v8.9.1
2 Dec 00:59:38 - [info] Windows_NT 10.0.16299 x64 LE
2 Dec 00:59:39 - [info] Loading palette nodes
2 Dec 00:59:40 - [info] Dashboard version 2.6.3-beta started at /ui
2 Dec 00:59:40 - [warn] ------------------------------------------------------
2 Dec 00:59:40 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
2 Dec 00:59:40 - [warn] [tail] Not currently supported on Windows.
2 Dec 00:59:40 - [warn] ------------------------------------------------------
2 Dec 00:59:40 - [info] Settings file  : \Users\Scott\.node-red\settings.js
2 Dec 00:59:40 - [info] User directory : \Users\Scott\.node-red
2 Dec 00:59:40 - [info] Flows file     : \Users\Scott\.node-red\flows_Asus2016.json
2 Dec 00:59:40 - [info] Server now running at http://127.0.0.1:1880/
2 Dec 00:59:40 - [info] Starting flows
2 Dec 00:59:40 - [info] Started flows
2 Dec 00:59:40 - [info] [mqtt-broker:8e9ad944.c14328] Connected to broker: NodeRed@mqtt://192.168.0.40:1883
2 Dec 01:05:29 - [info] Stopping modified flows
AlexaLocalNode closing done...
2 Dec 01:05:29 - [info] Stopped modified flows
2 Dec 01:05:29 - [info] Starting modified flows
2 Dec 01:05:29 - [info] Started modified flows
2 Dec 01:06:24 - [info] Stopping modified flows
2 Dec 01:06:24 - [info] Stopped modified flows
2 Dec 01:06:24 - [info] Starting modified flows
2 Dec 01:06:24 - [info] Started modified flows
8b8d625483bd4 Floor fan GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.41
Sending setup.xml to ::ffff:192.168.0.41
8b8d625483bd4 Floor fan GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.41
Sending setup.xml to ::ffff:192.168.0.41
8b8d625483bd4 Floor fan GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.41
Sending setup.xml to ::ffff:192.168.0.41
8b8d625483bd4 Floor fan GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.41
Sending setup.xml to ::ffff:192.168.0.41
8b8d625483bd4 Floor fan GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.41
Sending setup.xml to ::ffff:192.168.0.41
8b8d625483bd4 Floor fan GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.41
Sending setup.xml to ::ffff:192.168.0.41
8b8d625483bd4 Floor fan GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.41
Sending setup.xml to ::ffff:192.168.0.41
8b8d625483bd4 Floor fan GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.41
Sending setup.xml to ::ffff:192.168.0.41

**Comment by swilson86** [comment]
The main computer as shown above does not detect the node. I now have 2 stable platforms to help you resolve the problem. The clean Windows computer works okay, and the main computer with a lot of node red nodes does not.

**Comment by idumzaes** [comment]
If it helps, I’m running BananaPi Raspbian on a Pine64 board. 
I believe I’m having this issue because of the install directory location as I was having issues with two other packages I installed and I ended up purging altogether. 
I’m going to remove all Node-Red-Contrib-Alexa-Local packages and add them back later today to see if that fixes the issue. 
I’ll post the results when I get a change later tonight.

**Comment by idumzaes** [comment]
I deleted all related packages and directories and reinstalled it through the Pallete Settings. Added the nodes again and tried discovering devices again without success.
I'm not currently home and am working on it through my VPN, which is why I think I'm not having much success right now.
However, I did get more information from Node-Red logs after reinstalling... please find it below...
I'll try again tonight when I get home and I'll post a new log.

> 2 Dec 16:05:25 - [info] Server now running at http://127.0.0.1:1881/
> 2 Dec 16:05:25 - [info] Starting flows
> 2 Dec 16:05:26 - [info] Started flows
> 2 Dec 16:05:26 - [info] [mqtt-broker:5e587bfc.d6cc74] Connected to broker: mqtt://localhost:1883
> 2 Dec 16:05:26 - [info] [mqtt-broker:d3606e5.fa40a9] Connected to broker: mqtt://localhost:1883
> 2 Dec 16:06:02 - [info] Installing module: node-red-contrib-alexa-local, version: 0.3.8
> 2 Dec 16:06:14 - [info] Installed module: node-red-contrib-alexa-local
> 2 Dec 16:06:14 - [info] Added node types:
> 2 Dec 16:06:14 - [info]  - node-red-contrib-alexa-local:alexa-local
> 2 Dec 16:08:57 - [info] Stopping modified nodes
> 2 Dec 16:08:57 - [info] Stopped modified nodes
> 2 Dec 16:08:57 - [info] Starting modified nodes
> 2 Dec 16:08:57 - [info] Started modified nodes
> 8c90bc3f6708e8 Ceiling Light GET /upnp/amazon-ha-bridge/setup.xml ::ffff:10.8.0.2
> Sending setup.xml to ::ffff:10.8.0.2
> 8c90bc3f6708e8 Ceiling Light GET /upnp/amazon-ha-bridge/setup.xml ::ffff:10.8.0.2
> Sending setup.xml to ::ffff:10.8.0.2
> 8c90bc3f6708e8 Ceiling Light GET /upnp/amazon-ha-bridge/setup.xml ::ffff:10.8.0.2
> Sending setup.xml to ::ffff:10.8.0.2
> 8c90bc3f6708e8 Ceiling Light GET /upnp/amazon-ha-bridge/setup.xml ::ffff:10.8.0.2
> Sending setup.xml to ::ffff:10.8.0.2
> 8c90bc3f6708e8 Ceiling Light GET /upnp/amazon-ha-bridge/setup.xml ::ffff:10.8.0.2
> Sending setup.xml to ::ffff:10.8.0.2
> 8c90bc3f6708e8 Ceiling Light GET /upnp/amazon-ha-bridge/setup.xml ::ffff:10.8.0.2
> Sending setup.xml to ::ffff:10.8.0.2
> 8c90bc3f6708e8 Ceiling Light GET /upnp/amazon-ha-bridge/setup.xml ::ffff:10.8.0.2
> Sending setup.xml to ::ffff:10.8.0.2
> 8c90bc3f6708e8 Ceiling Light GET /upnp/amazon-ha-bridge/setup.xml ::ffff:10.8.0.2
> Sending setup.xml to ::ffff:10.8.0.2

**Comment by stephenhouser** [comment]
I've been having the same problem, where it looks like `setup.xml` is being sent but the Echo does not discover anything. My logs look similar to those directly above this message.

In searching around for other projects with similar problems, I see that `Sonoff-Tasmota` had a similar problem and (I've not tested) may have fixed it by with a case-sensitivity issue in the upnp response. [Sonoff-Tasmota Issue #854](https://github.com/arendst/Sonoff-Tasmota/pull/854). Perhaps this is a lead to solve the problem for this project.

**Comment by torinnguyen** [comment]
@stephenhouser noted on 'basic'.
@stephenhouser @idumzaes which version of Echo are you having problem with? I heard people are having issues with Echo Plus or Echo Pro. I don't have those models to verify this myself.

It does look like Echo is not happy with something inside /setup.xml response. There is no way to troubleshoot this, it's a guess game.
Anyway, I have made a small change in the latest version, please try again.

![image](https://user-images.githubusercontent.com/767320/33586201-b5203380-d99a-11e7-8fd9-f860ab33fd13.png)

**Comment by idumzaes** [comment]
I’m using the latest fire stick with Alexa. 
I updated to 0.3.10, deleted and recreate the nodes and still cannot be discovered. .
However, I’m no longer getting information about it in the logs.

**Comment by torinnguyen** [comment]
I don't know whether Alexa on FireStick has discovery capability. Does it actually work with other smart home hardware?

**Comment by idumzaes** [comment]
Yeah it does.

**Comment by torinnguyen** [comment]
like?

**Comment by idumzaes** [comment]
Nest and wink hub

**Comment by torinnguyen** [comment]
I'm getting information from google that FireStick does not support discovery (locally). It can only work with cloud-based devices. So please, first thing first, make sure Fire Stick has the capability to discovery a Philips Hue bridge LOCALLY before using this node. Otherwise, get a real Echo.

**Comment by Corundex** [comment]
Hi, 
It is not about discovery.
Correct responce (v. 0.3.2):

GET /api/u7unT3ubWCpIsyeya5mmsPONg2FGNBgsmrCWAhCR/lights HTTP/1.1
Host: 172.16.0.2:40677
Accept: */*

HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 05 Dec 2017 04:37:24 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{ "lights": { "51526620ee842": {"state": {"on": true, "bri": 126, "hue": 15823, "sat": 88, "effect": "none", "ct": 313, "alert": "none", "colormode": "ct", "ct": 365, "reachable": true, "xy": [0.4255, 0.3998]}, "type": "Extended color light", "name": "Basement light", "modelid": "LCT004", "manufacturername": "Philips", "uniqueid": "51526620ee842", "swversion": "65003148", "pointsymbol": {"1": "none", "2": "none", "3": "none", "4": "none", "5": "none", "6": "none", "7": "none", "8": "none"}}} }

Incorrect response (current version):
GET /api/u7unT3ubWCpIsyeya5mmsPONg2FGNBgsmrCWAhCR/lights HTTP/1.1
Host: 172.16.0.2:43837
Accept: */*

HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 05 Dec 2017 04:37:24 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{ "lights": { "d5188da9fd0c1": {"state": {"on": on, "bri": 126, "hue": 15823, "sat": 88, "effect": "none", "ct": 313, "alert": "none", "colormode": "ct", "ct": 365, "reachable": true, "xy": [0.4255, 0.3998]}, "type": "Extended color light", "name": "Ceiling light", "modelid": "LCT004", "manufacturername": "Philips", "uniqueid": "d5188da9fd0c1", "swversion": "65003148", "pointsymbol": {"1": "none", "2": "none", "3": "none", "4": "none", "5": "none", "6": "none", "7": "none", "8": "none"}}} }


the difference is ("on": true) vs. ("on": on).

Brs.

**Comment by starknetwork** [comment]
I have had a similar issue to that described in this thread. For me, alexa-local functionality stopped working a week ago, and I have been following this thread since. I have since realised that functionality stopped working for me after I replaced my (only) Echo Dot (latest gen), with an Echo (latest gen, not plus). I have plugged back in my echo dot, and functionality is working again. I am not sure if this is due to a conflict with the Echo, or if that pairing is somehow tied to the original device. As soon as I switch off the echo dot, functionality immediately stops from my other echo devices.

**Comment by torinnguyen** [comment]
that is the behavior Echo is designed to work. when you perform a device
discovery, the Echo that discovers that device will remember its
configurations. when you switch to a new Echo, it wont know how to control
those devices, you are supposed to perform a device discovery again.

This is how Echo works with any local devices. Cloud devices do not use
this behavior.

**Comment by starknetwork** [comment]
Just to clarify, I did attempt (multiple times) to re-discover the devices but it did not find them without the echo dot connected. I also created new flows from scratch in Node-red and it also did not discover them. Finally today i reconnected the echo dot, and it discovered all the new devices, as well as the originals, albeit, the originals were discovered as duplicates so I had to disable the original non working ones.

**Comment by starknetwork** [comment]
Further to this, I have just de-registered the echo dot, which has removed all the alexa-local devices. I have just done a discovery, and it does not find any of the alexa-local devices.

**Comment by stephenhouser** [comment]
I will test the latest version this evening.
Did you intend to close this issue? It appears to still be open and in testing.

**Comment by stephenhouser** [comment]
This issue is not resolved for my 2nd-gen Echo.

**Comment by swilson86** [comment]
I have given up on this software. It is not stable at this point.

**Comment by stephenhouser** [comment]
This issue is present in several other open source projects. Amazon appears to have changed something with their interaction with old hue bridges that has broken a lot of folks' systems. There appears to be no solution yet, anywhere I could find, for anyone.

Thus, it's not really the "stability" question for me, but the issue-closing without comment when it still exists. I'm grateful for the code and openness of the development and really do hope to re-adopt when it works for my devices.

In the meantime I have changed to [node-red-alexa-home-skill](https://www.npmjs.com/package/node-red-contrib-alexa-home-skill). I don't really like it though, as I have to create an account on their site and they (he) do not really have much documentation on what he might do with your information or how "secure" things there are.

**Comment by NoReasonToComplain** [comment]
Hi, I had the same issue. My solution was to buy a dot. Together with the dot my echo found the devices. Good solution for amazon.

**Comment by KlaatuVerataNecto** [comment]
I've tried the latest version (I believe it is 0.3.15) and it runs smoothly on Windows, Mac, Rpi. I only wasn't able to get it running in Docker container.
